OPENAI_API_KEY = "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"
OPENWEATHERMAP_API_KEY = "36665b36c426d00b7540e4e00fe11620"
